파이썬 입문(1분반) 기말고사 - 최규빈교수님

201514142 김동준 에너지화학공학과

#1

In [19]:
import pandas as pd
import numpy as np
import random as rd

def upgrade(day,usernum):
    success = [1,1,1,0,0,0,0,0,0,0]
    user = [0]
    while len(user) < day+1:
        if (user[-1] == 5):
            user.append(5)
        elif (rd.choice(success) == 1):
            user.append(user[-1]+1)
        else:
            user.append(user[-1])
    user_df = pd.DataFrame(user)
    user_df.columns=['user%s'%usernum]
    return(user_df)

def last(numd,numuser):
    lastday = pd.DataFrame({'0':[0]*(numd+1)})
    for numuser in range(1,numuser+1):
        lastday['user%s'%numuser] = upgrade(numd,numuser)
    lastdayreal=lastday.iloc[:,1:1000]
    return(lastdayreal)

In [20]:
last(62,100)

,user1,user2,user3,user4,user5,user6,user7,user8,user9,user10,...,user91,user92,user93,user94,user95,user96,user97,user98,user99,user100
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1
2,0,2,1,0,0,1,1,0,0,1,...,0,2,0,0,0,0,0,0,1,1
3,0,2,2,0,0,1,1,0,0,1,...,1,2,0,0,0,0,0,0,1,1
4,0,2,2,0,0,1,1,0,0,1,...,1,2,0,1,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
59,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
60,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
61,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
62,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5

#1 62일차에 강화를 성공한 사람의 수 계산 (행의 마지막의 bool형을 더하여 확인)

In [21]:
sum(last(62,100).iloc[-1,:] == 5)

100

_____________________________________

_____

#2 -(1),(2)

In [27]:
import pandas as pd
import numpy as np
import random as rd

success = [1,1,1,1,1,1,1,0,0,0]
def upgrade(day,usernum):
    user = [0]
    countzero = [0]
    while len(user) < day+1:
        if (user[-1] == 5):
            user.append(5)
        elif (rd.choice(success) == 0):
            user.append(user[-1])
            if (user[-1] == 0):
                continue
            else:    
                countzero[0] = countzero[0] + 1
        else:
            user.append(user[-1]+1)
            
        if countzero[0] == 2:
            user[-1] = 0
            countzero[0] = 0
        else:
            continue
        
    user_df = pd.DataFrame(user)
    user_df.columns=['user%s'%usernum]
    return(user_df)

def last(numd,numuser):
    lastday = pd.DataFrame({'0':[0]*(numd+1)})
    for numuser in range(1,numuser+1):
        lastday['user%s'%numuser] = upgrade(numd,numuser)
    lastdayreal=lastday.iloc[:,1:1000]
    return(lastdayreal)

In [28]:
last(62,100)

,user1,user2,user3,user4,user5,user6,user7,user8,user9,user10,...,user91,user92,user93,user94,user95,user96,user97,user98,user99,user100
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,1,1,0
2,2,1,1,1,2,1,2,1,1,2,...,2,2,2,2,2,1,1,2,2,0
3,3,1,0,2,2,2,2,0,2,3,...,3,3,3,2,3,1,2,3,3,0
4,3,0,1,3,3,3,3,0,3,4,...,4,4,4,3,3,2,3,4,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
59,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
60,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
61,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
62,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5

#2
(1) 이 경우 62일의 방학뒤에 100명의 유저중 대략 몇명정도 +5 강화상태에
있겠는가? 시뮬레이션을 활용하여 추론하라. (단, +5강화에 성공하지 못한 모
든 유저는 반드시 하루에 한번 강화를 시도해야 한다고 가정하자.)

last 에 numd = 62 , numuser = 100 대입

In [29]:
sum(last(62,100).iloc[-1,:] == 5)

100

___________________________________

___________________________________

(2) 31번째 시도 이후 대략 몇명의 유저가 +5 강화상태에 있겠는가?

last 에 numd = 31 , numuser = 100 대입

In [33]:
sum(last(31,100).iloc[-1,:] == 5)

97

________________________

___________________________________

#2 (3)

In [24]:
import pandas as pd
import numpy as np
import random as rd

success = [1,1,1,1,1,1,1,0,0,0]
def upgrade(day,usernum):
    user = [0]
    countzero = [0]
    while len(user) < day+1:
        if (user[-1] == 5):
            user.append(5)
        elif (rd.choice(success) == 0):
            user.append(user[-1])
            if (user[-1] == 0):
                continue
            else:    
                countzero[0] = countzero[0] + 1
        else:
            user.append(user[-1]+1)
            
        if countzero[0] == 2:
            user[-1] = 0
            countzero[0] = 0
        else:
            continue
        
    user_df = pd.DataFrame(user)
    user_df.columns=['user%s'%usernum]
    return(user_df)

def last(numd,numuser):
    lastday = pd.DataFrame({'0':[0]*(numd+1)})
    for numuser in range(1,numuser+1):
        lastday['user%s'%numuser] = upgrade(numd,numuser)
        if sum(lastday.iloc[-1,1:1000] == 5) >= 50:
            success = [1,1,1,1,1,1,1,1,1,0]
    lastdayreal=lastday.iloc[:,1:1000]
    return(lastdayreal)

In [25]:
last(62,100)

,user1,user2,user3,user4,user5,user6,user7,user8,user9,user10,...,user91,user92,user93,user94,user95,user96,user97,user98,user99,user100
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,1,1,1,1,1,0,1,...,0,0,1,0,1,1,1,1,1,0
2,1,0,2,2,1,2,2,2,0,1,...,1,1,2,0,1,2,2,2,1,0
3,2,1,3,2,2,2,2,3,1,2,...,2,2,3,1,0,3,3,2,0,1
4,0,2,3,3,3,3,3,4,2,3,...,3,3,4,2,1,3,4,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
59,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
60,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
61,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
62,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5

#2_(3)
100명의 유저중 50명이상의 유저가 +5 강화상태에 도달하는 순간 모든
유저의 강화성공확률을 90%로 증가시킨다고 하자. 62일의 방학뒤에 100명의
유저 중 몇명 정도가 +5 강화상태에 있겠는가?

last 에 numd = 62 , numuser = 100 대입

In [26]:
sum(last(62,100).iloc[-1,:] == 5)

100